
name: CI-Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:


jobs:
  run-tests:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2 # Step 1, takes our code from the Repo to the Build server

      - name: Setup Java 11
        uses: actions/setup-java@v2
        with:
          java-version: 11

      - name: Build and test with Maven
        run: mvn clean install

  second-job:
    runs-on: ubuntu-20.04

    steps:
      - name: Greet
        run: echo Hello from the Workflow
